experimentName: BOUTIQUE
useAnnotation: False
searchSpaceFile: params.yaml
trialCommand: python3 nni_test6.py
trialCodeDirectory: ../
trialGpuNumber: 0
trialConcurrency: 2
maxExperimentDuration: 12h
maxTrialNumber: 200
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: False