experimentName: BOUTIQUE
useAnnotation: False
searchSpaceFile: params5.yaml
trialCommand: python3 nni_test5.py
trialCodeDirectory: ./
trialGpuNumber: 0
trialConcurrency: 2
maxExperimentDuration: 24h
maxTrialNumber: 200
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: False