experimentName: BOUTIQUE
useAnnotation: False
searchSpaceFile: params.yaml
trialCommand: METRIC_NUM=1 python3 nni_test.py
trialCodeDirectory: ../
trialGpuNumber: 0
trialConcurrency: 2
maxExperimentDuration: 12h
maxTrialNumber: 100
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: False