searchSpace:
   hidden_size1:
      _type: randint
      _value: [2, 500]
   hidden_size2:
      _type: randint
      _value: [2, 500]
   hidden_size3:
      _type: randint
      _value: [2, 500]
   lr:
      _type: choice
      _value: [0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1]